---
title: "metagene"
output: html_notebook
version: 
---

```{r}
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicRanges")
biocLite("ggplot2")
biocLite("rtracklayer")
library("rtracklayer")
library("GenomicRanges")
library("ggplot2")
```

Constructing genomic intervals of interest
```{r}
source("/home/immd0754/Documents/R_things/General R scripts/metagene/regionlist_length_yeast_FUN.R")
res <- regionlist(plus=1000, minus=500, pos_strand="/home/immd0754/S_MELLOR/Rosa/pos_strand_annotations.bed", neg_strand="/home/immd0754/S_MELLOR/Rosa/neg_strand_annotations.bed")


promoter_region <- res$promoter_region
genes_plus <- res$genes_plus
genes_minus <- res$genes_minus


## Don't use at it is because it makes the promoter region list longer??
#source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/overlap1_FUN.R")
#promoter_region <- overlap1(promoter_region, genes_plus, genes_minus, minus=500)

```



Data import
```{r}
source("/home/immd0754/Documents/R_things/General R scripts/metagene/metagene_filelist_FUN.R")
filesbw <- filelist("/home/immd0754/S_MELLOR/Rosa/cerevisiae_dataForRosa", "uzun", MinPlus_ann=c("plus|posstrand|unipos","minus|negstrand|unimin"))
``` 






```{r}
b <- as.data.frame(test_bw)

l <- levels(b$seqnames)
l <- l[!l=="chrM"]

f <- (1:length(l))


for (i in 1:length(l)) {
  
  f[[i]] <- max(b[(b$seqnames==as.character(l[[i]])),]$end)
  
}

t <- lapply(f, function(x) vector("numeric", x))
names(t) <- l

for (i in 1:length(l)) {

t[[1]][b[(b$seqnames==as.character(l[[1]])),]$start:b[(b$seqnames==as.character(l[[1]])),]$end] <- b[(b$seqnames==as.character(l[[i]])),]$score

}


> for (i in 1:3) {
+ x[y2[i,1]:y2[i,2]] <- y[i,3]
+ }


``` 


```{r}
m <- matrix(NA, nrow=nrow(genes_minus), ncol=plus+minus+1)
rownames(m) <- genes_minus$V4

for (i in 1:nrow(m)) {
m[i,] <- t[[genes_minus$V1[i]]][genes_minus$V2[i]:genes_minus$V3[i]]
}
``` 






```{r}
gene_array <- array(data=NA, dim=c(nrow(promoter_region), length(filesbw), plus+minus), dimnames= list(promoter_region$V4, names(filesbw)))

for (f in 1:seq_len(length(filesbw))) {

    bigimp <- import.bw(filesbw[f])
    
  if (any(grep(MinPlus_ann[[2]], filesbw[f]))) {

        for (i in 1:20) {

            b <- as.data.frame(bigimp)
            b2 <- b[(b$seqnames==as.character(genes_minus$V1[[i]])),] # Specify chr. Added as.character because otherwise you're comparing factors and they don't have the same levels (because the bigwig file has chrM and promoter_region not), but maybe this is not the best solution
            b3 <- b2[b2$end>=genes_minus$V2[[i]],]
            b3 <- b3[b3$start<=(genes_minus$V3[[i]]-1),]
            
            if(sum(b3$width)>=minus+plus){
              b3[1,2] <- genes_minus$V2[[i]]
              b3[nrow(b3),3] <- (genes_minus$V3[[i]]-1)
              c <- rep(b3$score, times=((b3$end-b3$start)+1))
              
            } else if(max(b2$width)==1) {
              c <- vector("numeric", minus+plus) # fill this at position of b3$start with value score
              b3$start <- b3$start-genes_minus$V2[[i]]
              c[b3$start] <- b3$score
            } else {
              print("For now this doesn't work yet with this bw file, because it neither has continues values nor only the values with width 1. I'm sure you can solve it if you look in the second approach (after else if) an combine it with the first approach")
            }
            
            
            gene_array[as.character(genes_minus$V4[[i]]), f,] <- c
            }

    
      } else {
      if (any(grep(MinPlus_ann[[1]], filesbw[f]))) {
        strand(bigimp) <- "-"
      }else{
        print("no strand specification found")
      }
    }

}
    
```    

   


```{r}
















promoter_regionPlus <- genes_plus[(genes_plus$V3-genes_plus$V2)>1000,]

  source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/bin_genelist_FUN.R")
 listwv <- bin_matrix(promoter_region, binsize=5)
 bin_matrix <- listwv$bin_matrix
 bin_grange <- listwv$bin_grange
 numberbin <- listwv$numberbin

test2 <- matrix(data=NA, nrow=nrow(promoter_region), ncol = plus+minus)

s <- apply(test2, 1, promoter_region=promoter_region, test_s)
 
 
 
 
```

CountOverlap bit
```{r}
source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/countoverlap_fun.R", local=T)
binned_matrix <- overlapcount(bin_grange, filesbw, bin_matrix, MinPlus_ann=c("plus|posstrand|unipos","minus|negstrand|unimin"))

###Reverse rownames of negative strands: WORKS ONLY AS LONG AS genes_minus is first half, otherwise you have to change this bit
source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/rev1neg_fun.R", local=T)
stri_bins <- revneg(bin_matrix)



```



sum over bins

```{r}
source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/normalisiation_FUN.R")
binned_matrix <- normalisation(binned_matrix,numberbin)

source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/bin_sum_withapply_FUN.R")
metagene_table <- bin_sum(binned_matrix, stri_bins)

source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/combstrand_fun.R")
combined <- comstrand(metagene_table)



############ what has happened to genes that are overlapping. Multiple transcription start sites.
############ data is not normalised yet?
```


```{r}
source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/graph_samples_fun.R")
graph_samples(combined, plus=1000, minus=500, numberbin, name="booth")
```
















```{r}
#f <- function(x) length( intersect(seq(x[1],x[2],1), seq(x[3],x[4],1)) )

#a <- apply(X,1,f)






```




