---
title: "metagene"
output: html_notebook
version: 
---

```{r}
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicRanges")
biocLite("ggplot2")
biocLite("rtracklayer")
library("rtracklayer")
library("GenomicRanges")
library("ggplot2")
```

Constructing genomic intervals of interest
```{r}
#Genes according to Steinmetz lab Pechano et al. 2013
setwd("//biochstore4.bioch.ox.ac.uk/Mellor/Rosa")
genes_plus <- read.table("pos_strand_annotations.bed")
genes_minus <- read.table("neg_strand_annotations.bed")

#Specify region of interest
promoter_regionPlus <- genes_plus[]
promoter_regionPlus[,3] <- genes_plus[,2]+1000
promoter_regionPlus[,2] <- genes_plus[,2]-250

promoter_regionMinus <- genes_minus[]
promoter_regionMinus[,3] <- genes_minus[,3]+250
promoter_regionMinus[,2] <- genes_minus[,3]-1000

promoter_region <- rbind(promoter_regionMinus, promoter_regionPlus) ### don't change the order of minus/plus region without changing the renaming of the rownames of the minus strand just after the CountOverlap bit (chunk 5)

```



Data import
```{r}
filesbw <- dir("//biochstore4.bioch.ox.ac.uk/Mellor/Rosa/cerevisiae_dataForRosa", pattern = glob2rx("uzun*.bw"), full.names=TRUE)
#names(filesbw) <- file.path.sans.ext(filesbw)
names(filesbw) <- gsub('//biochstore4.bioch.ox.ac.uk/Mellor/Rosa/cerevisiae_dataForRosa|*_NETseq_minus.bw|*_NETseq_plus.bw|/uzun_*', '', filesbw)
``` 


Make a matrix with the bins for every gene
```{r}
rangelength <- promoter_region[1,3]-promoter_region[1,2]

#specify binsize in bp
binsize <- 5
numberbin <- rangelength/binsize

if (identical(round(numberbin), numberbin)) {
  
} else{
  print("The combination of genomic range and binsize makes the number of bins not an integer. So either change them or fix this problem in the code")
}


bin_matrix <- as.data.frame(matrix(nrow=(nrow(promoter_region)*numberbin), ncol=6))
colnames(bin_matrix) <- c("gene", "bin#", "chr", "start", "end", "strand")

bin_matrix[,1] <- rep(promoter_region[,4], each=numberbin)
bin_matrix[,2] <- rep(seq(1, numberbin), times=nrow(promoter_region))
bin_matrix[,3] <- rep(promoter_region[,1], each=numberbin)
bin_matrix[,6] <- rep(promoter_region[,6], each=numberbin)
bin_matrix[,4] <- rep(promoter_region[,2], each=numberbin)
bin_matrix[,4] <- bin_matrix[,4]+(binsize*(bin_matrix[,2]-1))
bin_matrix[,5] <- (bin_matrix[,4]+(binsize-1))


bin_grange <- makeGRangesFromDataFrame(bin_matrix, seqnames.field = "chr", start.field = "start", end.field = "end", keep.extra.columns = TRUE)
# Now bins are not overlapping (so have a  size of binsize in GRanges object) and the last bp in the promoter region is lost...
```

CountOverlap bit
```{r}

binned_matrix <- matrix(NA, nrow =  length(bin_grange), ncol = length(filesbw))

colnames(binned_matrix) <- names(filesbw)
rownames(binned_matrix) <- bin_matrix[,2] ### try to make it Bin + bin number


for (i in seq_len(length(filesbw))) {
  
  
  bigimp <- import.bw(filesbw[i])
  
  if (any(grep("plus", filesbw[i]))) {
  strand(bigimp) <- "+"
  } else {
    if (any(grep("minus", filesbw[i]))) {
    strand(bigimp) <- "-"
    }else{
  print("no strand specified")
  }
  }
  
  
  binned_matrix[,i] <- countOverlaps(bin_grange, bigimp)
}


###Reverse rownames of negative strands: WORKS ONLY AS LONG AS genes_minus is first half, otherwise you have to change this bit
rn <- rownames(binned_matrix)
rownames(binned_matrix) <- c(rev(rn[1:length(which(bin_matrix[,6]=="-"))]), rn[(length(which(bin_matrix[,6]=="-"))+1):length(rn)])

```



sum over bins

```{r}
metagene_table <- as.data.frame(matrix(NA, nrow=numberbin, ncol = length(filesbw)))
colnames(metagene_table) <- names(filesbw) 

for (i in 1:numberbin) { 
 for (j in 1:ncol(binned_matrix)) {

    metagene_table[i,j] <- mean(binned_matrix[which(row.names(binned_matrix)==i),j])

 }
}

############ what has happened to genes that are overlapping. Multiple transcription start sites.
############ data is not normalised yet?
```


Combine pos and neg strand
```{r}
combined_matrix <- as.data.frame(matrix(NA, nrow=numberbin, ncol = length(filesbw)/2))
combined_matrix[1:numberbin,1] <- colSums(metagene_table[1:2,1:2])
combined_matrix[,2] <- colSums(metagene_table[,3:4])


```


```{r}
#z <- ggplot(metagene_table, aes(y=metagene_table[,2], x=1:20))

#qplot(y=metagene_table[,6], x=1:80)

#z + geom_line()

#pointplot
#ggplot(data=metagene_table, aes(x=1:80)) + geom_point(aes(y=metagene_table[,1]), color="darkblue")+ geom_point(aes(y=metagene_table[,2]), color="red")+ geom_point(aes(y=metagene_table[,3]), color="orange")+ geom_point(aes(y=metagene_table[,4]), color= "cornflowerblue")+ geom_point(aes(y=metagene_table[,5]), colour="green")+ geom_point(aes(y=metagene_table[,6]), colour="purple") 

#lineplot
ggplot(data = metagene_table, aes(x=1:numberbin)) + geom_line(aes(y=metagene_table[,1], colour="dst1_minus"))+ geom_line(aes(y=metagene_table[,2], colour="dst1_plus"))+ geom_line(aes(y=metagene_table[,3], colour="spt4_minus"))+ geom_line(aes(y=metagene_table[,4], colour= "spt4_plus")) + scale_colour_manual("", breaks = c("dst1_minus", "dst1_plus", "spt4_minus","spt4_plus"), values = c("red", "green", "blue","cornflowerblue"))

ggplot(data = combined_matrix, aes(x=1:numberbin)) + geom_line(aes(y=combined_matrix[,1], colour="dst1"))+ geom_line(aes(y=combined_matrix[,2], colour="spt4"))+ scale_colour_manual("", breaks = c("dst1", "spt4"), values = c("orange","cornflowerblue"))

#+ geom_line(aes(y=metagene_table[,3], colour="spt4_minus"))+ geom_line(aes(y=metagene_table[,4], colour= "spt4_plus")) + scale_colour_manual("", breaks = c("dst1_minus", "dst1_plus", "spt4_minus","spt4_plus"), values = c("red", "green", "blue","cornflowerblue"))


#+ geom_line(aes(y=metagene_table[,5]), colour="green")+ geom_line(aes(y=metagene_table[,6]), colour="purple")+scale_fill_discrete(labels = c("1", "2", "3", "4", "5", "6"))+theme(legend.position="right")


#ggplot(data=metagene_table, aes(x=1:80, y=metagene_ta))
```
















```{r}
#f <- function(x) length( intersect(seq(x[1],x[2],1), seq(x[3],x[4],1)) )

#a <- apply(X,1,f)






```




