```{r}
overlap_array <- function(norm=FALSE, plus=1000, minus=500, pos_strand="/home/immd0754/S_MELLOR/Rosa/pos_strand_annotations.bed", neg_strand="/home/immd0754/S_MELLOR/Rosa/neg_strand_annotations.bed", bigwig_files_location="/home/immd0754/S_MELLOR/Rosa/cerevisiae_dataForRosa", name="", MinPlus_ann=c("plus|posstrand|unipos","minus|negstrand|unimin")) {
# Function that combines several functions to make an overview array of a certain number of bwfiles per gene
# Default plus=1000 and min=500 bp from TSS
# Default pos_strand and neg_strand are according to Pelechano et al Nature 2013, bigwig_files_location ="/home/immd0754/S_MELLOR/Rosa/cerevisiae_dataForRosa 
# Default name is an emtpy string so would be good to put something there
# Default MinPlus_ann=c("plus|posstrand|unipos","minus|negstrand|unimin"), if the correct plus/minus isn't included ("no strand specified") alter this
# Default is no normalisation, if you want to normalise set norm to TRUE  
    
  source("/home/immd0754/Documents/R_things/General R scripts/metagene/regionlist_length_yeast_FUN.R")
  res <- regionlist(plus, minus, pos_strand, neg_strand)
  
  promoter_region <- res$promoter_region
  genes_plus <- res$genes_plus
  genes_minus <- res$genes_minus
  
  
  source("/home/immd0754/Documents/R_things/General R scripts/metagene/filelist_FUN.R")
  filesbw <- filelist(bigwig_files_location, name, MinPlus_ann)
  
  
  source("/home/immd0754/Documents/R_things/General R scripts/metagene/bw_to_countmatrix_FUN.R")
  overview_sum <- bw_to_countmatrix(filesbw, genes_minus, genes_plus, plus, minus, MinPlus_ann)
  
  overview <- overview_sum$overview_exl
  sum_exl_read_dens <- overview_sum$sum_exl_read_dens
  
  source("/home/immd0754/Documents/R_things/General R scripts/metagene/rev_neg_array_FUN.R")
  overview <- rev_neg_array(overview, genes_minus, sum_exl_read_dens)
  
  
  if (norm==TRUE) {
  source("/home/immd0754/Documents/R_things/General R scripts/metagene/normalise_array_FUN.R")
  overview <- normalise_array(overview, filesbw)
  } else {}
  
  return(overview)
  
  
  
}

```


```{r}

l <- overlap_array(name="uzun", norm = TRUE)

select <- droplevels(genes[sum_exl_read_dens])
```
