---
title: "metagene"
output: html_notebook
version: 
---

```{r}
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicRanges")
biocLite("ggplot2")
biocLite("rtracklayer")
library("rtracklayer")
library("GenomicRanges")
library("ggplot2")
```

############ what has happened to genes that are overlapping. Multiple transcription start sites.
############ data is not normalised yet?


"//biochstore4.bioch.ox.ac.uk/Mellor/Rosa/cerevisiae_dataForRosa"

source for functions



```{r}
metageneplot <- function(bigwig_files_location, name, plus, minus, pos_strand="//biochstore4.bioch.ox.ac.uk/Mellor/Rosa/pos_strand_annotations.bed", neg_strand="//biochstore4.bioch.ox.ac.uk/Mellor/Rosa/neg_strand_annotations.bed", binsize=5) {
  
  source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/geneslist.R", local=T)
  source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/metagene_filelist.R", local=T)
  source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/bin_genelist.R", local=T)
  source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/countoverlap_fun.R", local=T)
  source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/revneg_fun.R", local=T)
  source("C:/Users/immd0754/Documents/R_things/General R scripts/metagene/metatable_fun.R", local=T)

##### Define region of interest
promoter_region <- regionlist(plus, minus, pos_strand, neg_strand)
  
##### Data import
filesbw <- filelist(bigwig_files_location, name)


##### Make a matrix with the bins for every gene

 matrix_grange <- bin_matrix(promoter_region, binsize)
 bin_matrix <- matrix_grange$bin_matrix
 bin_grange <- matrix_grange$bin_grange
 numberbin <- matrix_grange$numberbin

#### CountOverlap bit

binned_matrix <- overlapcount(bin_grange, filesbw, bin_matrix)

###Reverse rownames of negative strands: WORKS ONLY AS LONG AS genes_minus is first half, otherwise you have to change this bit
binned_matrix <- revneg(binned_matrix, bin_matrix)

### sum over bins
metagene_table <- metatable(numberbin, filesbw, binned_matrix)


###Plot bit
#lineplot
ggplot(data = metagene_table, aes(x=1:numberbin)) + geom_line(aes(y=metagene_table[,1], colour="dst1_minus"))+ geom_line(aes(y=metagene_table[,2], colour="dst1_plus"))+ geom_line(aes(y=metagene_table[,3], colour="spt4_minus"))+ geom_line(aes(y=metagene_table[,4], colour= "spt4_plus")) + scale_colour_manual("", breaks = c("dst1_minus", "dst1_plus", "spt4_minus","spt4_plus"), values = c("red", "green", "blue","cornflowerblue"))

}

```


```{r}
metageneplot("//biochstore4.bioch.ox.ac.uk/Mellor/Rosa/cerevisiae_dataForRosa", "uzun", plus=1500, minus=500)



```





